### ISSUE TITLE
how can i use this lib to get the mobi cover image?

### ISSUE THREAD

**Issue by buzai** [bfabiszewski/libmobi#6]

**Comment by bfabiszewski** [comment]
Please have a look at [this example](https://github.com/bfabiszewski/QLMobi/blob/1a5b92b28ad1474242b1cbd4641ad3e009869396/QLMobi/BAFMobi.m#L230).

**Comment by buzai** [comment]
i see this function（dataForCover） i think it return  the data of cover image , but how can i kown save it to jpg or png type?

**Comment by bfabiszewski** [comment]
You need to save the memory buffer to disk. You also need to detect the format of the image.
The details are up to you, programming language you use, and so on.

**Comment by buzai** [comment]
@bfabiszewski 
Thank you very much. I've been troubled by this problem for several days. Before your answer, I thought there would be a place to look up the picture format of the cover. Now I see, I need to judge the format of the picture from the buffer.

**Comment by bfabiszewski** [comment]
There is also another way to get the cover image. See [partForCover example](https://github.com/bfabiszewski/QLMobi/blob/master/QLMobi/BAFMobi.m#L204).
In this case the library will detect the image format for you. The drawback is that it needs more time and resources, because you first need to parse the document and all its resources.

[See here](https://github.com/bfabiszewski/libmobi/blob/public/tools/mobitool.c#L454) for example how to get resource type from MOBIPart resource.

**Comment by buzai** [comment]
Very good, in fact, I have roughly 10G of the Mobi file, I want analysis of these documents cover, title and other information, and then stores them into the database, so I feel a little bit slower should be acceptable.
